### ISSUE TITLE
Diagnose warnings

### ISSUE THREAD

**Issue by fdhidalgo** [fdhidalgo/rais_data_rcode#1]
When I run the `clean_rais`, I get a bunch of warnings, mostly about factors. What is causing this? And is there anything that can/should be done so that they warnings don't appear? 

Here is the output I get:

```
Warning messages:
1: Unknown levels in `f`: 22, 32, 33
2: In eval(jsub, SDenv, parent.frame()) : NAs introduced by coercion
3: In eval(jsub, SDenv, parent.frame()) : NAs introduced by coercion
4: Unknown levels in `f`: 6, 7, 8, 9, 10
5: Unknown levels in `f`: 0
6: Unknown levels in `f`: 10, 11
7: Unknown levels in `f`: 26, 27, 28, 29, 40, 44, 46, 47, 51, 60, 61, 62, 70, 80
8: Unknown levels in `f`: 9
9: Unknown levels in `f`: 9
10: Unknown levels in `f`: 1090, 1198, 1201, 1210, 2005, 2020, 2070, 2100, 2216, 2275, 2283, 2291, 2992, 3018, 3026, 3130, 3220, 3239, 3247, 4030, 4049, 4057, 4065, 4073, 4080, 4111, 4995, 5010, 5029, 5037,  -1
11: Unknown levels in `f`: 22, 32, 33
12: In eval(jsub, SDenv, parent.frame()) : NAs introduced by coercion
13: In eval(jsub, SDenv, parent.frame()) : NAs introduced by coercion
14: Unknown levels in `f`: 6, 7, 8, 9, 10
15: Unknown levels in `f`: 0
16: Unknown levels in `f`: 10, 11
17: Unknown levels in `f`: 26, 27, 28, 29, 40, 44, 46, 47, 51, 60, 61, 62, 70, 80
18: Unknown levels in `f`: 9
19: Unknown levels in `f`: 9
20: Unknown levels in `f`: 1090, 1198, 1201, 1210, 2005, 2020, 2070, 2100, 2216, 2275, 2283, 2291, 2992, 3018, 3026, 3130, 3220, 3239, 3247, 4030, 4049, 4057, 4065, 4073, 4080, 4111, 4995, 5010, 5029, 5037,  -1
```

**Comment by emgriggs** [comment]
So I am pretty sure the answer to this is that the factor commands from forcats output a warning error if there is nothing that matches the factor in the data.  So if the data that is ran through it has no observations with the level of 6, it outputs a warning. I assume this will fix itself when we run the entirety of the data through because the different levels will probably be all represented. 
The other error–In eval(jsub, SDenv, parent.frame())– is one that comes from forcing the variables into numeric format. I believe that when you force a variable into numeric, any additional values that are weird are forced into N/As.  I forced four variables into numerics because the original stata code did so.
